services:

  db:
    image: postgres:18
    container_name: rendatop-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql
    
  redis:
    image: redis:7
    container_name: rendatop-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./.data/redis:/data


  # evolution:
  #   container_name: evolution_api
  #   image: atendai/evolution-api:v2.2.3
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./.data/evolution:/evolution/instances

  whatsapp-wwebjs:
    image: avoylenko/wwebjs-api:v1.34.6
    container_name: rendatop-whatsapp-wwebjs
    restart: always
    env_file:
      - .env
    environment:
      - API_KEY=${WHATSAPP_WWEBJS_API_KEY}
      - ENABLE_WEBHOOK=FALSE
      - ENABLE_LOCAL_CALLBACK_EXAMPLE=FALSE
    volumes:
      - ./.data/wwebjs:/usr/src/app/sessions
    ports:
      - "3003:3000"
    
  migrator:
    build:
      context: ./
      dockerfile: ./migrator/Dockerfile
    container_name: rendatop-migrator
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    restart: "no"

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: rendatop-client
    restart: always
    expose:
      - "4173"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: rendatop-nginx
    restart: always
    ports:
      - "80:80"
    

  landing:
    build:
      context: ./landing
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BASE_URL_SERVER: ${BASE_URL_SERVER}
    container_name: rendatop-landing
    restart: always
    ports:
      - "3001:3000"
    
