// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server.Domain;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260328184138_subscription_scheduled_cancellation")]
    partial class subscription_scheduled_cancellation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("server.Domain.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cnpj");

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("banks");
                });

            modelBuilder.Entity("server.Domain.IPCA", b =>
                {
                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<decimal>("value")
                        .HasColumnType("numeric");

                    b.HasKey("date");

                    b.ToTable("ipcas");
                });

            modelBuilder.Entity("server.Domain.Investment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("archived")
                        .HasColumnType("boolean");

                    b.Property<Guid>("bank_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("date_buy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("due_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("index")
                        .HasColumnType("integer");

                    b.Property<decimal>("index_percent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("index_value")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ownerid")
                        .HasColumnType("uuid");

                    b.Property<bool>("taxes")
                        .HasColumnType("boolean");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("value")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.HasIndex("bank_id");

                    b.HasIndex("ownerid");

                    b.ToTable("investments");
                });

            modelBuilder.Entity("server.Domain.Notification", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_read")
                        .HasColumnType("boolean");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("read_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("source_key")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("server.Domain.RecurringInvestment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<Guid>("bank_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("day_of_month")
                        .HasColumnType("integer");

                    b.Property<int?>("duration_days")
                        .HasColumnType("integer");

                    b.Property<int>("frequency")
                        .HasColumnType("integer");

                    b.Property<int>("index")
                        .HasColumnType("integer");

                    b.Property<decimal>("index_percent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("index_value")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("last_generated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("liquidity_daily")
                        .HasColumnType("boolean");

                    b.Property<string>("months_csv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("owner_id")
                        .HasColumnType("uuid");

                    b.Property<bool>("taxes")
                        .HasColumnType("boolean");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("value")
                        .HasColumnType("numeric");

                    b.PrimitiveCollection<List<short>>("weekdays")
                        .IsRequired()
                        .HasColumnType("smallint[]");

                    b.HasKey("id");

                    b.HasIndex("bank_id");

                    b.HasIndex("owner_id");

                    b.ToTable("recurring_investments");
                });

            modelBuilder.Entity("server.Domain.Redemption", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("investmentid")
                        .HasColumnType("uuid");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("value")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.HasIndex("investmentid");

                    b.ToTable("redemptions");
                });

            modelBuilder.Entity("server.Domain.Selic", b =>
                {
                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<decimal>("value")
                        .HasColumnType("numeric");

                    b.HasKey("date");

                    b.ToTable("selics");
                });

            modelBuilder.Entity("server.Domain.Subscription", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("cancel_at_period_end")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("cancellation_requested_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("current_period_end")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("current_period_start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("mp_card_id")
                        .HasColumnType("text");

                    b.Property<string>("mp_customer_id")
                        .HasColumnType("text");

                    b.Property<string>("mp_payment_id")
                        .HasColumnType("text");

                    b.Property<string>("payment_method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("plan_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("subscriptions");
                });

            modelBuilder.Entity("server.Domain.SubscriptionCharge", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("approved_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("billing_period_end")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("billing_period_start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("boleto_barcode_content")
                        .HasColumnType("text");

                    b.Property<string>("boleto_barcode_image_base64")
                        .HasColumnType("text");

                    b.Property<string>("boleto_digitable_line")
                        .HasColumnType("text");

                    b.Property<string>("boleto_url")
                        .HasColumnType("text");

                    b.Property<string>("charge_kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("due_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("payer_cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("payment_method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pix_qr_code")
                        .HasColumnType("text");

                    b.Property<string>("pix_qr_code_base64")
                        .HasColumnType("text");

                    b.Property<string>("plan_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("provider_external_reference")
                        .HasColumnType("text");

                    b.Property<string>("provider_payment_id")
                        .HasColumnType("text");

                    b.Property<string>("provider_status_detail")
                        .HasColumnType("text");

                    b.Property<DateTime?>("receipt_sent_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("reminder_sent_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("subscription_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("subscription_id");

                    b.HasIndex("user_id");

                    b.ToTable("subscription_charges");
                });

            modelBuilder.Entity("server.Domain.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("calendar_public_enabled")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("calendar_public_token")
                        .HasColumnType("uuid");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email_verification_secret")
                        .HasColumnType("text");

                    b.Property<DateTime?>("email_verification_sent_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("email_verified")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("notify_email")
                        .HasColumnType("boolean");

                    b.Property<bool>("notify_telegram")
                        .HasColumnType("boolean");

                    b.Property<bool>("notify_whatsapp")
                        .HasColumnType("boolean");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("totp_enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("totp_secret")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("server.Domain.Investment", b =>
                {
                    b.HasOne("server.Domain.Bank", "bank")
                        .WithMany()
                        .HasForeignKey("bank_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Domain.User", "owner")
                        .WithMany()
                        .HasForeignKey("ownerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bank");

                    b.Navigation("owner");
                });

            modelBuilder.Entity("server.Domain.Notification", b =>
                {
                    b.HasOne("server.Domain.User", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("server.Domain.RecurringInvestment", b =>
                {
                    b.HasOne("server.Domain.Bank", "bank")
                        .WithMany()
                        .HasForeignKey("bank_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Domain.User", "owner")
                        .WithMany()
                        .HasForeignKey("owner_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bank");

                    b.Navigation("owner");
                });

            modelBuilder.Entity("server.Domain.Redemption", b =>
                {
                    b.HasOne("server.Domain.Investment", "investment")
                        .WithMany("redemptions")
                        .HasForeignKey("investmentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("investment");
                });

            modelBuilder.Entity("server.Domain.Subscription", b =>
                {
                    b.HasOne("server.Domain.User", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("server.Domain.SubscriptionCharge", b =>
                {
                    b.HasOne("server.Domain.Subscription", "subscription")
                        .WithMany("subscription_charges")
                        .HasForeignKey("subscription_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Domain.User", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("subscription");

                    b.Navigation("user");
                });

            modelBuilder.Entity("server.Domain.Investment", b =>
                {
                    b.Navigation("redemptions");
                });

            modelBuilder.Entity("server.Domain.Subscription", b =>
                {
                    b.Navigation("subscription_charges");
                });
#pragma warning restore 612, 618
        }
    }
}
