// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server.Domain;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260708141902_mercado_pago_hosted_checkout_subscriptions")]
    partial class mercado_pago_hosted_checkout_subscriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("server.Domain.AiUsage", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("feature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("user_id", "feature", "created_at");

                    b.ToTable("ai_usages");
                });

            modelBuilder.Entity("server.Domain.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cnpj");

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("banks");
                });

            modelBuilder.Entity("server.Domain.BlogPost", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("author_user_id")
                        .HasColumnType("uuid");

                    b.Property<string>("author_user_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("body_html")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("body_text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("cover_asset_id")
                        .HasColumnType("uuid");

                    b.Property<string>("cover_image_data_url")
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("excerpt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("published_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("author_user_id");

                    b.HasIndex("slug")
                        .IsUnique();

                    b.HasIndex("updated_at");

                    b.HasIndex("status", "published_at");

                    b.ToTable("blog_posts");
                });

            modelBuilder.Entity("server.Domain.BlogPostAsset", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("alt_text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("blog_post_id")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("content_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("file_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("size_bytes")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("blog_post_id");

                    b.ToTable("blog_post_assets");
                });

            modelBuilder.Entity("server.Domain.BlogPostSocialPublication", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("blog_post_id")
                        .HasColumnType("uuid");

                    b.Property<string>("channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("error_message")
                        .HasColumnType("text");

                    b.Property<DateTime?>("published_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("remote_post_id")
                        .HasColumnType("text");

                    b.Property<string>("remote_url")
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("blog_post_id", "channel")
                        .IsUnique();

                    b.ToTable("blog_post_social_publications");
                });

            modelBuilder.Entity("server.Domain.BrowserPushSubscription", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("auth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("p256dh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("user_agent")
                        .HasColumnType("text");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("endpoint")
                        .IsUnique();

                    b.HasIndex("user_id");

                    b.ToTable("browser_push_subscriptions");
                });

            modelBuilder.Entity("server.Domain.IPCA", b =>
                {
                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<decimal>("value")
                        .HasColumnType("numeric");

                    b.HasKey("date");

                    b.ToTable("ipcas");
                });

            modelBuilder.Entity("server.Domain.Investment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("archived")
                        .HasColumnType("boolean");

                    b.Property<Guid>("bank_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("date_buy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("due_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("index")
                        .HasColumnType("integer");

                    b.Property<decimal>("index_percent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("index_value")
                        .HasColumnType("numeric");

                    b.Property<int?>("investment_type")
                        .HasColumnType("integer");

                    b.Property<Guid?>("money_box_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ownerid")
                        .HasColumnType("uuid");

                    b.Property<bool>("taxes")
                        .HasColumnType("boolean");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("value")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("wallet_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("bank_id");

                    b.HasIndex("money_box_id");

                    b.HasIndex("ownerid");

                    b.HasIndex("wallet_id");

                    b.ToTable("investments");
                });

            modelBuilder.Entity("server.Domain.LandingVisit", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ip_address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("referrer")
                        .HasColumnType("text");

                    b.Property<string>("user_agent")
                        .HasColumnType("text");

                    b.Property<string>("visit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("created_at");

                    b.HasIndex("visit");

                    b.ToTable("landing_visits");
                });

            modelBuilder.Entity("server.Domain.MoneyBox", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("owner_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("owner_id");

                    b.ToTable("money_boxes");
                });

            modelBuilder.Entity("server.Domain.Notification", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_read")
                        .HasColumnType("boolean");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("read_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("source_key")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("server.Domain.RecurringInvestment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<Guid>("bank_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("day_of_month")
                        .HasColumnType("integer");

                    b.Property<int?>("duration_days")
                        .HasColumnType("integer");

                    b.Property<int>("frequency")
                        .HasColumnType("integer");

                    b.Property<int>("index")
                        .HasColumnType("integer");

                    b.Property<decimal>("index_percent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("index_value")
                        .HasColumnType("numeric");

                    b.Property<int?>("investment_type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("last_generated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("liquidity_daily")
                        .HasColumnType("boolean");

                    b.Property<string>("months_csv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("owner_id")
                        .HasColumnType("uuid");

                    b.Property<bool>("taxes")
                        .HasColumnType("boolean");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("value")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("wallet_id")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<short>>("weekdays")
                        .IsRequired()
                        .HasColumnType("smallint[]");

                    b.HasKey("id");

                    b.HasIndex("bank_id");

                    b.HasIndex("owner_id");

                    b.HasIndex("wallet_id");

                    b.ToTable("recurring_investments");
                });

            modelBuilder.Entity("server.Domain.Redemption", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("investmentid")
                        .HasColumnType("uuid");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("value")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.HasIndex("investmentid");

                    b.ToTable("redemptions");
                });

            modelBuilder.Entity("server.Domain.Selic", b =>
                {
                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<decimal>("value")
                        .HasColumnType("numeric");

                    b.HasKey("date");

                    b.ToTable("selics");
                });

            modelBuilder.Entity("server.Domain.Subscription", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("cancel_at_period_end")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("cancellation_requested_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("current_period_end")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("current_period_start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("mp_card_id")
                        .HasColumnType("text");

                    b.Property<string>("mp_customer_id")
                        .HasColumnType("text");

                    b.Property<string>("mp_payment_id")
                        .HasColumnType("text");

                    b.Property<string>("mp_preapproval_id")
                        .HasColumnType("text");

                    b.Property<string>("payment_method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("plan_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("subscriptions");
                });

            modelBuilder.Entity("server.Domain.SubscriptionCharge", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("approved_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("billing_period_end")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("billing_period_start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("boleto_barcode_content")
                        .HasColumnType("text");

                    b.Property<string>("boleto_barcode_image_base64")
                        .HasColumnType("text");

                    b.Property<string>("boleto_digitable_line")
                        .HasColumnType("text");

                    b.Property<string>("boleto_url")
                        .HasColumnType("text");

                    b.Property<string>("charge_kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("due_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("payer_cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("payment_method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pix_qr_code")
                        .HasColumnType("text");

                    b.Property<string>("pix_qr_code_base64")
                        .HasColumnType("text");

                    b.Property<string>("plan_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("provider_checkout_url")
                        .HasColumnType("text");

                    b.Property<string>("provider_external_reference")
                        .HasColumnType("text");

                    b.Property<string>("provider_payment_id")
                        .HasColumnType("text");

                    b.Property<string>("provider_status_detail")
                        .HasColumnType("text");

                    b.Property<string>("provider_subscription_id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("receipt_sent_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("reminder_sent_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("subscription_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("subscription_id");

                    b.HasIndex("user_id");

                    b.ToTable("subscription_charges");
                });

            modelBuilder.Entity("server.Domain.SupportTicket", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("archived_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("last_message_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("requester_user_email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("requester_user_id")
                        .HasColumnType("uuid");

                    b.Property<string>("requester_user_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("archived_at", "last_message_at");

                    b.HasIndex("requester_user_id", "status");

                    b.HasIndex("status", "last_message_at");

                    b.ToTable("support_tickets");
                });

            modelBuilder.Entity("server.Domain.SupportTicketMessage", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("body_html")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("body_text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("sender_user_id")
                        .HasColumnType("uuid");

                    b.Property<string>("sender_user_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sender_user_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ticket_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("sender_user_id");

                    b.HasIndex("ticket_id", "created_at");

                    b.ToTable("support_ticket_messages");
                });

            modelBuilder.Entity("server.Domain.SupportTicketMessageAttachment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("content_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("file_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_image")
                        .HasColumnType("boolean");

                    b.Property<Guid>("message_id")
                        .HasColumnType("uuid");

                    b.Property<long>("size_bytes")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("message_id");

                    b.ToTable("support_ticket_message_attachments");
                });

            modelBuilder.Entity("server.Domain.SupportTicketStatusHistory", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("actor_user_id")
                        .HasColumnType("uuid");

                    b.Property<string>("actor_user_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("from_status")
                        .HasColumnType("text");

                    b.Property<string>("source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ticket_id")
                        .HasColumnType("uuid");

                    b.Property<string>("to_status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("actor_user_id");

                    b.HasIndex("ticket_id", "created_at");

                    b.ToTable("support_ticket_status_history");
                });

            modelBuilder.Entity("server.Domain.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("auth_provider")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool>("calendar_public_enabled")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("calendar_public_token")
                        .HasColumnType("uuid");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email_verification_secret")
                        .HasColumnType("text");

                    b.Property<DateTime?>("email_verification_sent_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("email_verified")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("notify_browser")
                        .HasColumnType("boolean");

                    b.Property<bool>("notify_email")
                        .HasColumnType("boolean");

                    b.Property<bool>("notify_telegram")
                        .HasColumnType("boolean");

                    b.Property<bool>("notify_whatsapp")
                        .HasColumnType("boolean");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pending_email")
                        .HasColumnType("text");

                    b.Property<string>("pending_email_verification_secret")
                        .HasColumnType("text");

                    b.Property<DateTime?>("pending_email_verification_sent_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("telegram_chat_id")
                        .HasColumnType("text");

                    b.Property<bool>("totp_enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("totp_secret")
                        .HasColumnType("text");

                    b.Property<int>("user_type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("server.Domain.Wallet", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("owner_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("owner_id");

                    b.HasIndex("owner_id", "name")
                        .IsUnique();

                    b.ToTable("wallets");
                });

            modelBuilder.Entity("server.Domain.AiUsage", b =>
                {
                    b.HasOne("server.Domain.User", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("server.Domain.BlogPost", b =>
                {
                    b.HasOne("server.Domain.User", "author_user")
                        .WithMany()
                        .HasForeignKey("author_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("author_user");
                });

            modelBuilder.Entity("server.Domain.BlogPostAsset", b =>
                {
                    b.HasOne("server.Domain.BlogPost", "blog_post")
                        .WithMany("assets")
                        .HasForeignKey("blog_post_id");

                    b.Navigation("blog_post");
                });

            modelBuilder.Entity("server.Domain.BlogPostSocialPublication", b =>
                {
                    b.HasOne("server.Domain.BlogPost", "blog_post")
                        .WithMany("social_publications")
                        .HasForeignKey("blog_post_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("blog_post");
                });

            modelBuilder.Entity("server.Domain.BrowserPushSubscription", b =>
                {
                    b.HasOne("server.Domain.User", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("server.Domain.Investment", b =>
                {
                    b.HasOne("server.Domain.Bank", "bank")
                        .WithMany()
                        .HasForeignKey("bank_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Domain.MoneyBox", "money_box")
                        .WithMany()
                        .HasForeignKey("money_box_id");

                    b.HasOne("server.Domain.User", "owner")
                        .WithMany()
                        .HasForeignKey("ownerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Domain.Wallet", "wallet")
                        .WithMany()
                        .HasForeignKey("wallet_id");

                    b.Navigation("bank");

                    b.Navigation("money_box");

                    b.Navigation("owner");

                    b.Navigation("wallet");
                });

            modelBuilder.Entity("server.Domain.MoneyBox", b =>
                {
                    b.HasOne("server.Domain.User", "owner")
                        .WithMany()
                        .HasForeignKey("owner_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("owner");
                });

            modelBuilder.Entity("server.Domain.Notification", b =>
                {
                    b.HasOne("server.Domain.User", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("server.Domain.RecurringInvestment", b =>
                {
                    b.HasOne("server.Domain.Bank", "bank")
                        .WithMany()
                        .HasForeignKey("bank_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Domain.User", "owner")
                        .WithMany()
                        .HasForeignKey("owner_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Domain.Wallet", "wallet")
                        .WithMany()
                        .HasForeignKey("wallet_id");

                    b.Navigation("bank");

                    b.Navigation("owner");

                    b.Navigation("wallet");
                });

            modelBuilder.Entity("server.Domain.Redemption", b =>
                {
                    b.HasOne("server.Domain.Investment", "investment")
                        .WithMany("redemptions")
                        .HasForeignKey("investmentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("investment");
                });

            modelBuilder.Entity("server.Domain.Subscription", b =>
                {
                    b.HasOne("server.Domain.User", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("server.Domain.SubscriptionCharge", b =>
                {
                    b.HasOne("server.Domain.Subscription", "subscription")
                        .WithMany("subscription_charges")
                        .HasForeignKey("subscription_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Domain.User", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("subscription");

                    b.Navigation("user");
                });

            modelBuilder.Entity("server.Domain.SupportTicket", b =>
                {
                    b.HasOne("server.Domain.User", "requester_user")
                        .WithMany()
                        .HasForeignKey("requester_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("requester_user");
                });

            modelBuilder.Entity("server.Domain.SupportTicketMessage", b =>
                {
                    b.HasOne("server.Domain.User", "sender_user")
                        .WithMany()
                        .HasForeignKey("sender_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Domain.SupportTicket", "ticket")
                        .WithMany("messages")
                        .HasForeignKey("ticket_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sender_user");

                    b.Navigation("ticket");
                });

            modelBuilder.Entity("server.Domain.SupportTicketMessageAttachment", b =>
                {
                    b.HasOne("server.Domain.SupportTicketMessage", "message")
                        .WithMany("attachments")
                        .HasForeignKey("message_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("message");
                });

            modelBuilder.Entity("server.Domain.SupportTicketStatusHistory", b =>
                {
                    b.HasOne("server.Domain.User", "actor_user")
                        .WithMany()
                        .HasForeignKey("actor_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Domain.SupportTicket", "ticket")
                        .WithMany("status_history")
                        .HasForeignKey("ticket_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("actor_user");

                    b.Navigation("ticket");
                });

            modelBuilder.Entity("server.Domain.Wallet", b =>
                {
                    b.HasOne("server.Domain.User", "owner")
                        .WithMany()
                        .HasForeignKey("owner_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("owner");
                });

            modelBuilder.Entity("server.Domain.BlogPost", b =>
                {
                    b.Navigation("assets");

                    b.Navigation("social_publications");
                });

            modelBuilder.Entity("server.Domain.Investment", b =>
                {
                    b.Navigation("redemptions");
                });

            modelBuilder.Entity("server.Domain.Subscription", b =>
                {
                    b.Navigation("subscription_charges");
                });

            modelBuilder.Entity("server.Domain.SupportTicket", b =>
                {
                    b.Navigation("messages");

                    b.Navigation("status_history");
                });

            modelBuilder.Entity("server.Domain.SupportTicketMessage", b =>
                {
                    b.Navigation("attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
