// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server.Domain;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260310005712_bankColor")]
    partial class bankColor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("server.Domain.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cnpj");

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("banks");
                });

            modelBuilder.Entity("server.Domain.IPCA", b =>
                {
                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<decimal>("value")
                        .HasColumnType("numeric");

                    b.HasKey("date");

                    b.ToTable("ipcas");
                });

            modelBuilder.Entity("server.Domain.Investment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("bank_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("date_buy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("due_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("index")
                        .HasColumnType("integer");

                    b.Property<decimal>("index_percent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("index_value")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ownerid")
                        .HasColumnType("uuid");

                    b.Property<bool>("taxes")
                        .HasColumnType("boolean");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("value")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.HasIndex("bank_id");

                    b.HasIndex("ownerid");

                    b.ToTable("investments");
                });

            modelBuilder.Entity("server.Domain.Redemption", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("investmentid")
                        .HasColumnType("uuid");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("value")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.HasIndex("investmentid");

                    b.ToTable("redemptions");
                });

            modelBuilder.Entity("server.Domain.Selic", b =>
                {
                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<decimal>("value")
                        .HasColumnType("numeric");

                    b.HasKey("date");

                    b.ToTable("selics");
                });

            modelBuilder.Entity("server.Domain.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("server.Domain.Investment", b =>
                {
                    b.HasOne("server.Domain.Bank", "bank")
                        .WithMany()
                        .HasForeignKey("bank_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Domain.User", "owner")
                        .WithMany()
                        .HasForeignKey("ownerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bank");

                    b.Navigation("owner");
                });

            modelBuilder.Entity("server.Domain.Redemption", b =>
                {
                    b.HasOne("server.Domain.Investment", "investment")
                        .WithMany("redemptions")
                        .HasForeignKey("investmentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("investment");
                });

            modelBuilder.Entity("server.Domain.Investment", b =>
                {
                    b.Navigation("redemptions");
                });
#pragma warning restore 612, 618
        }
    }
}
