<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-android</TargetFramework>

		<OutputType>Exe</OutputType>
		<RootNamespace>RendaTop.App</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<NoWarn>$(NoWarn);NU1900</NoWarn>
		<NuGetAudit>false</NuGetAudit>
		<_AndroidBuildRuntimeIdentifiersInParallel>false</_AndroidBuildRuntimeIdentifiersInParallel>

		<!-- Display name -->
		<ApplicationTitle>RendaTop</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>br.com.rendatop.app</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0.8</ApplicationDisplayVersion>
		<ApplicationVersion>9</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">29.0</SupportedOSPlatformVersion>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" Color="#111827" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#111827" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\bank_logo_*.svg" Resize="False" />
		<MauiImage Update="Resources\Images\brand_icon.svg" Resize="True" BaseSize="128,128" />
		
		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.60" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.0" />
		<PackageReference Include="Microcharts.Maui" Version="1.0.1" />
		<PackageReference Include="Plugin.Maui.Calendar" Version="3.0.2" />
	</ItemGroup>

</Project>
